Cylix/cpp_redis

examples/redis_client.cpp
includes/cpp_redis/network/io_service.hpp
sources/network/io_service.cpp

add boost asio worker to keep io service loop alive

---

sources/network/tcp_client.cpp

There is a race in the TCP client when connecting to the Redis host. The std::condition_variable is notified before the m_is_connected boolean is toggled possibly causing the connection to fail. This appears to happen very frequently in my setup.

fix race condition in tcp_client::connect

---

.gitignore

By doing so, we make sure that the process of building the code does not imply a change to the git repository itself.

Ignoring Makefile created by CMake process.

---

includes/cpp_redis/redis_client.hpp
sources/redis_client.cpp

`cpp_redis::redis_client` is not single threaded, meaning that the callback could be called from the `io_service` threads. Allowing a custom callback to call `reply_callback_t` can be handy when you need thread-safety.
**Example when the current approach could fail:**
```cpp
my_http_server.get("/user", [](request& req, reply& rep) {
// This is handled in the http_server_thread
redis.get("session_hash:" + req.session, [rep](cpp_redis::reply& rep) {
// This is handled in the redis_client_thread! :(
rep.send(rep.as_string());
}
});
```
**How the proposed change can help:**
```cpp
// Sets a before callback for cpp_redis::redis_client
redis.before_callback([this](cpp_redis::reply& reply, const cpp_redis::redis_client::reply_callback_t& callback) {
// Thread-safely enqueue the reply in the http …
```

allow custom callback before calling reply_callback_t

---

sources/network/unix/io_service.cpp

Just fixing up four warnings that show up when compiling under Xcode 8.1.

Fixing casting warnings on macOS

---

sources/network/windows_impl/io_service.cpp

Due to the fact that socket map was cleared in disconnect method of tcp_client and completion port was signaled only if socket map was not empty all io threads were waiting forever to get the signal. This would potentially lead to a deadlock on shutdown in case redis client would run in a separate thread that would properly wait for destructor to finis.

Fix deadlock in win io_service

---

.gitignore
CMakeLists.txt
cpp_redis.pc.in

[pkg-config](https://www.freedesktop.org/wiki/Software/pkg-config) is a common tool to generate compiler flags for libraries on a system. This PR adds the relevant config file so other projects can use pkg-config to discover where cpp_redis has been installed to.

Generate pkg-config File

---

examples/CMakeLists.txt
examples/future_client.cpp
examples/sync_client.cpp
includes/cpp_redis/cpp_redis
includes/cpp_redis/future_client.hpp
includes/cpp_redis/sync_client.hpp
sources/future_client.cpp
sources/sync_client.cpp

This adds two new clients. The "future_client" presents an asynchronous interface using C++11 std::future types, and the "sync_client" presents a synchronous interface. Both sit atop the original "redis_client" and are fully backward compatible.

Added future and sync clients

---

examples/redis_subscriber.cpp
includes/cpp_redis/redis_client.hpp
tests/sources/spec/redis_client_spec.cpp
tests/sources/spec/redis_subscriber_spec.cpp

Avoid using typedef names over full specialization.
Same as mentioned in [tacopie](https://github.com/Cylix/tacopie/pull/3).
It has been also tested on VS 2013 and 2015.
[]'s

Fix std::atomic compilation errors (C2797) on msvc 2013 (again)

---

includes/cpp_redis/future_client.hpp
includes/cpp_redis/redis_client.hpp
includes/cpp_redis/sync_client.hpp
sources/redis_client.cpp

Changes for #36.
Overload all the Z** related functions to provide int, double and string versions concerning the min/max/incr parameters.

Z set functions floating point value handling

---

CMakeLists.txt
includes/cpp_redis/future_client.hpp
includes/cpp_redis/network/redis_connection.hpp
includes/cpp_redis/redis_client.hpp
includes/cpp_redis/redis_subscriber.hpp
sources/network/redis_connection.cpp
sources/redis_client.cpp
sources/redis_subscriber.cpp

Fix a bug introduced in release 3.2.0 and reported in #61 .
The bug occurs when a `redis_client` or a `redis_subscriber` is initialized as a global data.
It introduced a static initialization order fiasco condition due to a conflict between the initialization of the `redis_client` and the initialization of an internal global variable, `get_tcp_client`, which is supposed to be used during the initialization.
In order to solve that, the design has been reviewed in order to not use the global variable `get_tcp_client`, but instead an additional constructor in `redis_client` and `redis_subscriber` (and forward that parameter to the `redis_connection` where the issue occurs).
These additional constructors are only provided for the very specific case where the user do not wish to use `tacopie` …

Fix release 3.2.0

---

CMakeLists.txt

Useful for CMake configs like "Debug" or "RelWithDebInfo". It avoids a
MSVC warning when one tries to link to the library from an own project.

Produce and install PDB (debug symbols) on Windows

---

sources/network/redis_connection.cpp
sources/redis_client.cpp
tests/sources/spec/redis_client_spec.cpp
tests/sources/spec/redis_subscriber_spec.cpp

Fix issue #70.
* update ref to tacopie (fix reconnection issue)
* do not clear buffered commands/callbacks when trying to commit/sync_commit during disconnection (more convenient and consistent with .send behavior)
* fix deadlock issue on .sycn_commit during reconnection
* update tests to reflect changes

Fix reconnect behavior

---

examples/redis_client.cpp
includes/cpp_redis/network/tcp_client_iface.hpp
includes/cpp_redis/redis_client.hpp
sources/redis_client.cpp

Hi, Thank for your work.
Today, I use your repo in company, but I can't find zadd command and then I found the the page [#57](https://github.com/Cylix/cpp_redis/issues/57), hope you like this pr.

add zadd command

---

CMakeLists.txt

This will use the installed tacopie if available, which fixes issue #92.

Use installed tacopie

---

CMakeLists.txt
includes/cpp_redis/future_client.hpp
includes/cpp_redis/redis_client.hpp
sources/future_client.cpp
sources/redis_client.cpp

fix zadd params (change from const to const&). Also add zadd to future_client and remove temporary gtest fix as gtest is now fixed.
fix #99.

ZADD const& and future_client impl

---

examples/CMakeLists.txt

Add `-pthread` flag to `CMAKE_CXX_FLAGS`, otherwise, when set  `DBUILD_EXAMPLES=true`, there would be compile error.
```
/usr/local/lib/libtacopie.a(io_service.cpp.o): In function `tacopie::io_service::io_service()':
io_service.cpp:(.text+0xac1): undefined reference to `pthread_create'
/usr/local/lib/libtacopie.a(thread_pool.cpp.o): In function `tacopie::utils::thread_pool::thread_pool(unsigned long)':
thread_pool.cpp:(.text+0x88b): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
examples/CMakeFiles/cpp_redis_subscriber.dir/build.make:96: recipe for target 'bin/cpp_redis_subscriber' failed
make[2]: *** [bin/cpp_redis_subscriber] Error 1
CMakeFiles/Makefile2:167: recipe for target 'examples/CMakeFiles/cpp_redis_subscriber.dir/all' failed
make[1]: *** …
```

To avoid compile error when `DBUILD_EXAMPLES=true`.

---

CMakeLists.txt

Should default to `STATIC`, and if shared libraries are desired, use the  `-DBUILD_SHARED_LIBS=ON` cmake option

Remove explicit STATIC in add_library call so dynamic libraries can be built

---

CMakeLists.txt
examples/CMakeLists.txt
tests/CMakeLists.txt

This PR makes all the CMakeLists a bit nicer and removes ambiguity over how to format things.

Use uniform CMake spacing and capitalization

---

README.md

.commit() is for async calls.
sub.sync_commit() doesn't exist on the latest version.

fixing .README errors

---

CMakeLists.txt

found when `__CPP_REDIS_LOGGING_ENABLED` was set, but `__TACOPIE_LOGGING_ENABLED` was not, and we couldn't see any cpp_redis logs ...

reset the SOURCES var so that the tacopie project won't include the cpp_redis sources too

---

includes/cpp_redis/core/sentinel.hpp
includes/cpp_redis/impl/client.ipp

Extra unnecessary semicolons removed.

Fix errors that appear when compiling with `-pedantic-errors` flag.

---

sources/core/client.cpp
sources/core/sentinel.cpp
sources/core/subscriber.cpp

Using [cppcheck](https://github.com/danmar/cppcheck) I have found redundant calls of copy constructors for caught exception during rethrowing.

Fix redundant copy of caught exception

---

WORKSPACE

This will make it so the original version of cpp_redis depends on the original version of tacopie, and not my fork.

bazel workspace: change to cylix's tacopie
